/**
 * CHEMICAL INORGANIC PARAMETERS
 *
 * Parameters related to inorganic chemical water quality.
 * Includes pH, alkalinity, hardness, metals, chlorides, sulfates, silica.
 */

import type { ParameterDefinition } from "../types";

export const chemicalInorganicParameters: ParameterDefinition[] = [
	{
		id: "ph",
		label: "pH",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "number",
		defaultValue: 7.2,
		typicalRange: { min: 0, max: 14 },
		description: "Water acidity or alkalinity",
		tags: ["ph", "acidity", "chemical"],
		suggestedSource: "imported",
		required: true,
		validationRule: (value) => Number(value) >= 0 && Number(value) <= 14,
		validationMessage: "pH must be between 0 and 14",
	},
	{
		id: "alkalinity",
		label: "Total Alkalinity",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "mg/L CaCO₃",
		availableUnits: ["mg/L CaCO₃", "ppm"],
		defaultValue: 120,
		typicalRange: { min: 0, max: 500 },
		description: "Water buffer capacity",
		tags: ["alkalinity", "buffer"],
		suggestedSource: "imported",
	},
	{
		id: "hardness",
		label: "Total Hardness",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		relevantSubsectors: ["hotel", "food_service"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "mg/L CaCO₃",
		availableUnits: ["mg/L CaCO₃", "ppm", "°dH"],
		defaultValue: 180,
		typicalRange: { min: 0, max: 500 },
		description: "Calcium and magnesium concentration",
		tags: ["hardness", "calcium", "magnesium", "scaling"],
		suggestedSource: "imported",
	},
	{
		id: "iron",
		label: "Total Iron",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial"],
		importance: "optional",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm", "µg/L"],
		defaultValue: 0.8,
		typicalRange: { min: 0, max: 5 },
		description: "Dissolved and particulate iron concentration",
		tags: ["iron", "metals", "staining"],
		suggestedSource: "imported",
	},
	{
		id: "manganese",
		label: "Manganese",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial"],
		importance: "optional",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm", "µg/L"],
		defaultValue: 0.15,
		typicalRange: { min: 0, max: 2 },
		description: "Manganese concentration",
		tags: ["manganese", "metals", "staining"],
		suggestedSource: "imported",
	},
	{
		id: "chlorides",
		label: "Chlorides",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "industrial"],
		importance: "optional",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 150,
		typicalRange: { min: 0, max: 1000 },
		description: "Chloride concentration - indicates salinity",
		tags: ["chlorides", "salinity", "corrosion"],
		suggestedSource: "imported",
	},
	{
		id: "sulfates",
		label: "Sulfates",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "industrial"],
		importance: "optional",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 100,
		typicalRange: { min: 0, max: 500 },
		description: "Sulfate concentration",
		tags: ["sulfates", "scaling"],
		suggestedSource: "imported",
	},
	{
		id: "silica",
		label: "Silica",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["industrial"],
		importance: "optional",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 20,
		typicalRange: { min: 0, max: 200 },
		description: "Silica concentration - causes boiler scaling",
		tags: ["silica", "scaling", "boiler"],
		suggestedSource: "imported",
	},

	// Heavy Metals
	{
		id: "cadmium",
		label: "Cadmium (Cd)",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["industrial", "municipal"],
		relevantSubsectors: ["oil_gas"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "µg/L"],
		defaultValue: 0,
		typicalRange: { min: 0, max: 0.1 },
		description:
			"Cadmium concentration - highly toxic heavy metal, strictly regulated",
		tags: ["heavy-metal", "toxic", "cadmium", "cd"],
		suggestedSource: "imported",
		required: false,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "Cadmium must be non-negative",
	},
	{
		id: "chromium",
		label: "Chromium (Cr)",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["industrial", "municipal"],
		relevantSubsectors: ["oil_gas"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "µg/L"],
		defaultValue: 0,
		typicalRange: { min: 0, max: 2.0 },
		description: "Chromium concentration (total) - includes Cr(III) and Cr(VI)",
		tags: ["heavy-metal", "toxic", "chromium", "cr"],
		suggestedSource: "imported",
		required: false,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "Chromium must be non-negative",
	},
	{
		id: "lead",
		label: "Lead (Pb)",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["industrial", "municipal"],
		relevantSubsectors: ["oil_gas"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "µg/L"],
		defaultValue: 0,
		typicalRange: { min: 0, max: 0.5 },
		description:
			"Lead concentration - toxic heavy metal, common in industrial wastewater",
		tags: ["heavy-metal", "toxic", "lead", "pb"],
		suggestedSource: "imported",
		required: false,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "Lead must be non-negative",
	},
	{
		id: "mercury",
		label: "Mercury (Hg)",
		category: "chemical-inorganic",
		targetSection: "water-quality",
		relevantSectors: ["industrial", "municipal"],
		relevantSubsectors: ["oil_gas"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "µg/L"],
		defaultValue: 0,
		typicalRange: { min: 0, max: 0.01 },
		description:
			"Mercury concentration - extremely toxic, bioaccumulative heavy metal",
		tags: ["heavy-metal", "toxic", "mercury", "hg"],
		suggestedSource: "imported",
		required: false,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "Mercury must be non-negative",
	},
];
