/**
 * CHEMICAL ORGANIC PARAMETERS
 *
 * Parameters related to organic chemical water quality.
 * Includes BOD, COD, FOG, nutrients, hydrocarbons.
 */

import type { ParameterDefinition } from "../types";

export const chemicalOrganicParameters: ParameterDefinition[] = [
	{
		id: "bod5",
		label: "BOD₅ (Biochemical Oxygen Demand)",
		category: "chemical-organic",
		targetSection: "water-quality",
		relevantSectors: ["industrial", "municipal"],
		relevantSubsectors: ["food_service"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 300,
		typicalRange: { min: 0, max: 5000 },
		description: "Oxygen consumed by microorganisms in 5 days",
		tags: ["bod", "organic", "biodegradable"],
		suggestedSource: "imported",
		required: true,
	},
	{
		id: "cod",
		label: "COD (Chemical Oxygen Demand)",
		category: "chemical-organic",
		targetSection: "water-quality",
		relevantSectors: ["industrial", "municipal"],
		relevantSubsectors: ["food_service", "textile_manufacturing"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 600,
		typicalRange: { min: 0, max: 10000 },
		description: "Oxygen required for chemical oxidation",
		tags: ["cod", "organic", "oxidation"],
		suggestedSource: "imported",
		required: true,
	},
	{
		id: "fats-oils-greases",
		label: "Fats, Oils and Grease (FOG)",
		category: "chemical-organic",
		targetSection: "water-quality",
		relevantSectors: ["industrial"],
		relevantSubsectors: ["food_service"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 150,
		typicalRange: { min: 0, max: 1000 },
		description: "FOG content - critical in food industry",
		tags: ["fats", "oils", "grease", "fog"],
		suggestedSource: "imported",
	},
	{
		id: "nitrogen-total",
		label: "Total Nitrogen",
		category: "chemical-organic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "industrial"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 40,
		typicalRange: { min: 0, max: 200 },
		description: "Total nitrogen concentration",
		tags: ["nitrogen", "nutrients"],
		suggestedSource: "imported",
	},
	{
		id: "phosphorus-total",
		label: "Total Phosphorus",
		category: "chemical-organic",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "industrial"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 8,
		typicalRange: { min: 0, max: 50 },
		description: "Total phosphorus concentration",
		tags: ["phosphorus", "nutrients"],
		suggestedSource: "imported",
	},
	{
		id: "tph",
		label: "Total Petroleum Hydrocarbons (TPH)",
		category: "chemical-organic",
		targetSection: "water-quality",
		relevantSectors: ["industrial"],
		relevantSubsectors: ["oil_gas"],
		importance: "critical",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm", "µg/L"],
		defaultValue: 0,
		typicalRange: { min: 0, max: 100 },
		description:
			"Total petroleum hydrocarbons - regulatory requirement for oil & gas operations",
		tags: ["hydrocarbons", "petroleum", "tph", "oil"],
		suggestedSource: "imported",
		required: true,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "TPH must be non-negative",
	},
];
