/**
 * DESIGN PARAMETERS
 *
 * Parameters related to project design, context, and configuration.
 * Includes project information, objectives, and design criteria.
 */

import type { ParameterDefinition } from "../types";

export const designParameters: ParameterDefinition[] = [
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// PROJECT CONTEXT FIELDS
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{
		id: "water-source",
		label: "Primary Water Source",
		category: "design",
		targetSection: "project-context",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "combobox",
		defaultValue: "",
		description: "Main water source - determines treatment strategy",
		tags: ["water", "source", "origin"],
		suggestedSource: "manual",
		required: true,
		options: [
			"Municipal Network",
			"Private Well",
			"Surface Water (river, lake)",
			"Rainwater Harvesting",
			"Internal Purification System",
		],
		placeholder: "Select or type water source...",
	},
	{
		id: "water-uses",
		label: "Main Water Uses",
		category: "design",
		targetSection: "project-context",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "tags",
		defaultValue: [],
		description:
			"How water will be used in the operation (can select multiple)",
		tags: ["uses", "application", "purpose"],
		suggestedSource: "manual",
		required: true,
		options: [
			"Potable Water / Human Consumption",
			"Industrial Processes",
			"Cleaning and Sanitation",
			"Cooling / HVAC",
			"Steam Generation (boilers)",
			"Irrigation",
			"Pools and SPA",
			"Laundry",
			"Kitchens / Food Preparation",
			"Other",
		],
	},
	{
		id: "existing-system",
		label: "Existing Treatment System?",
		category: "design",
		targetSection: "project-context",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "select",
		defaultValue: "",
		description: "Determines if this is an upgrade or new installation",
		tags: ["existing", "upgrade", "retrofit"],
		suggestedSource: "manual",
		required: true,
		options: ["Yes", "No"],
	},
	{
		id: "existing-system-description",
		label: "Current System Description",
		category: "design",
		targetSection: "project-context",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "recommended",
		type: "text",
		defaultValue: "",
		multiline: true,
		description: "Current technologies and processes (if applicable)",
		tags: ["existing", "system", "description"],
		suggestedSource: "manual",
		placeholder:
			"e.g., Sand Filter + Reverse Osmosis, Activated Sludge, MBR, etc.",
	},
	{
		id: "project-objective",
		label: "Main Project Objective",
		category: "design",
		targetSection: "project-context",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "combobox",
		defaultValue: "",
		description: "Primary priority that will guide the design",
		tags: ["objective", "goal", "priority"],
		suggestedSource: "manual",
		required: true,
		options: [
			"Comply with discharge regulations",
			"Reduce environmental footprint / Sustainability",
			"Save costs / ROI",
			"Ensure water availability",
		],
		placeholder: "Select or type objective...",
	},
	{
		id: "reuse-goals",
		label: "Reuse or Discharge Goals",
		category: "design",
		targetSection: "project-context",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "tags",
		defaultValue: [],
		description: "Final use of treated water (can select multiple)",
		tags: ["reuse", "discharge", "effluent"],
		suggestedSource: "manual",
		required: true,
		options: [
			"Landscape Irrigation",
			"Toilet Flushing",
			"Industrial Process Reuse",
			"Cleaning Operations",
			"Comply with discharge regulations only",
			"Aquifer Recharge",
			"Other",
		],
	},
	{
		id: "discharge-point",
		label: "Current Discharge Point",
		category: "design",
		targetSection: "project-context",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "recommended",
		type: "combobox",
		defaultValue: "",
		description: "Where wastewater is currently discharged",
		tags: ["discharge", "effluent", "outlet"],
		suggestedSource: "manual",
		options: [
			"Municipal Sewer",
			"Natural Water Body (river, lake, sea)",
			"Absorption Well / Infiltration",
			"No Discharge (evaporation or total reuse)",
		],
		placeholder: "Select or type discharge point...",
	},

	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// ECONOMICS & SCALE FIELDS
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{
		id: "water-cost",
		label: "Current Water Cost",
		category: "operational",
		targetSection: "economics-scale",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "unit",
		defaultUnit: "USD/m³",
		availableUnits: ["USD/m³", "EUR/m³", "USD/L", "EUR/L", "USD/gal", "CRC/m³"],
		defaultValue: "",
		description: "Current water tariff (for ROI and economic feasibility)",
		tags: ["cost", "tariff", "economics"],
		suggestedSource: "manual",
		required: true,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "Cost must be greater than or equal to 0",
	},
	{
		id: "water-consumption",
		label: "Water Consumption",
		category: "operational",
		targetSection: "economics-scale",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "unit",
		defaultUnit: "m³/day",
		availableUnits: ["m³/day", "m³/month", "L/day", "gal/day", "gal/month"],
		defaultValue: "",
		description: "Average water consumption",
		tags: ["consumption", "usage", "demand"],
		suggestedSource: "manual",
		required: true,
		validationRule: (value) => Number(value) > 0,
		validationMessage: "Consumption must be greater than 0",
	},
	{
		id: "wastewater-generated",
		label: "Wastewater Generated",
		category: "operational",
		targetSection: "economics-scale",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "unit",
		defaultUnit: "m³/day",
		availableUnits: ["m³/day", "m³/month", "L/day", "gal/day", "gal/month"],
		defaultValue: "",
		description: "Volume of wastewater requiring treatment",
		tags: ["wastewater", "effluent", "discharge"],
		suggestedSource: "manual",
		required: true,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "Volume must be greater than or equal to 0",
	},
	{
		id: "people-served-daily",
		label: "People Served Daily",
		category: "operational",
		targetSection: "economics-scale",
		relevantSectors: ["municipal", "commercial", "residential"],
		importance: "recommended",
		type: "select",
		defaultValue: "",
		description: "Employees, customers, residents served daily",
		tags: ["people", "population", "users"],
		suggestedSource: "manual",
		options: [
			"< 20",
			"20 - 50",
			"50 - 200",
			"200 - 500",
			"500 - 1,000",
			"1,000 - 2,000",
			"2,000 - 5,000",
			"> 5,000",
		],
	},
	{
		id: "people-served-exact",
		label: "Exact Number of People (Optional)",
		category: "operational",
		targetSection: "economics-scale",
		relevantSectors: ["municipal", "commercial", "residential"],
		importance: "optional",
		type: "number",
		defaultValue: "",
		description: "If you prefer to give an exact number instead of the range",
		tags: ["people", "population", "exact"],
		suggestedSource: "manual",
		validationRule: (value) => !value || Number(value) > 0,
		validationMessage: "Number must be greater than 0",
	},
	{
		id: "peak-factor",
		label: "Peak Factor / Peak Consumption Rate",
		category: "operational",
		targetSection: "economics-scale",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "recommended",
		type: "number",
		defaultValue: "",
		description:
			"Ratio between peak and average flow (e.g., 1.8 means peak is 1.8x average)",
		tags: ["peak", "factor", "variation", "flow"],
		suggestedSource: "manual",
		typicalRange: { min: 1.0, max: 4.0 },
		validationRule: (value) =>
			!value || (Number(value) >= 1.0 && Number(value) <= 5.0),
		validationMessage: "Peak factor must be between 1.0 and 5.0",
	},

	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// PROJECT CONSTRAINTS FIELDS
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{
		id: "constraints",
		label: "Main Constraints",
		category: "design",
		targetSection: "project-constraints",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "tags",
		defaultValue: [],
		description:
			"Factors that limit or condition the system design (select all that apply)",
		tags: ["constraints", "limitations", "restrictions"],
		suggestedSource: "manual",
		required: true,
		options: [
			"Limited space for installation",
			"Very strict regulations",
			"Complex water quality (high hardness, salinity, metals)",
			"Limited or unstable electrical supply",
			"Complicated sludge/waste management",
			"Critical OPEX (minimize energy, chemicals, labor)",
			"No significant restrictions",
		],
		placeholder: "Select all applicable constraints",
	},
	{
		id: "regulatory-requirements",
		label: "Regulatory Requirements / Standards",
		category: "regulatory",
		targetSection: "project-constraints",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "recommended",
		type: "tags",
		defaultValue: [],
		description: "List regulations/standards this project must comply with",
		tags: ["regulation", "standard", "norm", "compliance", "law"],
		suggestedSource: "manual",
		options: [
			// México
			"NOM-001 (MX - Discharge)",
			"NOM-002 (MX - Rivers)",
			"NOM-003 (MX - Reuse)",
			"NOM-127 (MX - Drinking)",
			// Costa Rica
			"RTCR-25991 (CR - Drinking)",
			"Reglamento Vertido (CR)",
			// USA
			"EPA Clean Water Act (US)",
			"EPA NPDWR (US - Drinking)",
			"EPA 40 CFR 503 (US - Biosolids)",
			// International
			"WHO Guidelines (Drinking)",
			// Europe
			"EU 2020/2184 (Drinking)",
			"EU 91/271 (Urban WW)",
			// Other
			"Not Applicable",
		],
		placeholder: "Select or type regulations (e.g., NOM-001, EPA 40 CFR...)",
	},

	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// FIELD NOTES
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{
		id: "field-notes",
		label: "Engineer Notes",
		category: "operational",
		targetSection: "field-notes",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "recommended",
		type: "text",
		defaultValue: "",
		multiline: true,
		description:
			"These notes will appear in the proposal context to justify technical decisions",
		tags: ["notes", "observations", "remarks"],
		suggestedSource: "manual",
		placeholder:
			"Record site findings, identified risks, client agreements, relevant technical assumptions...",
	},

	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	// DESIGN PARAMETERS (General Data)
	// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	{
		id: "design-flow",
		label: "Design Flow",
		category: "design",
		targetSection: "general-data",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "critical",
		type: "unit",
		defaultUnit: "L/s",
		availableUnits: ["L/s", "m³/h", "m³/d", "GPM", "MGD"],
		defaultValue: 50,
		typicalRange: { min: 1, max: 10000 },
		description: "Maximum flow rate the system must process",
		tags: ["flow", "design", "capacity"],
		suggestedSource: "manual",
		required: true,
		validationRule: (value) => Number(value) > 0,
		validationMessage: "Flow must be greater than 0",
	},
	{
		id: "population-served",
		label: "Population Served",
		category: "design",
		targetSection: "general-data",
		relevantSectors: ["municipal", "residential"],
		importance: "critical",
		type: "unit",
		defaultUnit: "inhabitants",
		availableUnits: ["inhabitants"],
		defaultValue: 25000,
		description: "Number of people served by the system",
		tags: ["population", "demographics"],
		suggestedSource: "manual",
		required: true,
	},
	{
		id: "storage-capacity",
		label: "Storage Capacity",
		category: "design",
		targetSection: "general-data",
		relevantSectors: ["municipal", "commercial", "industrial"],
		importance: "optional",
		type: "unit",
		defaultUnit: "m³",
		availableUnits: ["m³", "L", "gal"],
		description: "Storage tank capacity",
		tags: ["storage", "tank", "capacity"],
		suggestedSource: "manual",
	},
];
