/**
 * PHYSICAL PARAMETERS
 *
 * Parameters related to physical water quality characteristics.
 * Includes turbidity, color, temperature, TSS, TDS, conductivity.
 */

import type { ParameterDefinition } from "../types";

export const physicalParameters: ParameterDefinition[] = [
	{
		id: "turbidity",
		label: "Turbidity",
		category: "physical",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial"],
		importance: "critical",
		type: "unit",
		defaultUnit: "NTU",
		availableUnits: ["NTU", "FAU", "FTU"],
		defaultValue: 15,
		typicalRange: { min: 0, max: 100 },
		description: "Measure of water clarity - suspended particles",
		tags: ["turbidity", "clarity", "filtration"],
		suggestedSource: "imported",
		required: true,
		validationRule: (value) => Number(value) >= 0,
		validationMessage: "Turbidity must be ≥ 0",
	},
	{
		id: "color",
		label: "Apparent Color",
		category: "physical",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial"],
		relevantSubsectors: ["textile_manufacturing"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "UPC",
		availableUnits: ["UPC", "Pt-Co", "Hazen"],
		defaultValue: 25,
		typicalRange: { min: 0, max: 500 },
		description: "Color intensity in water",
		tags: ["color", "aesthetic"],
		suggestedSource: "imported",
	},
	{
		id: "temperature",
		label: "Temperature",
		category: "physical",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "°C",
		availableUnits: ["°C", "°F"],
		defaultValue: 25,
		typicalRange: { min: 0, max: 40 },
		description: "Water temperature",
		tags: ["temperature", "thermal"],
		suggestedSource: "imported",
	},
	{
		id: "tss",
		label: "Total Suspended Solids (TSS)",
		category: "physical",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "industrial"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 250,
		typicalRange: { min: 0, max: 1000 },
		description: "Suspended solids concentration",
		tags: ["solids", "suspended", "filtration"],
		suggestedSource: "imported",
	},
	{
		id: "tds",
		label: "Total Dissolved Solids (TDS)",
		category: "physical",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial"],
		importance: "recommended",
		type: "unit",
		defaultUnit: "mg/L",
		availableUnits: ["mg/L", "ppm"],
		defaultValue: 500,
		typicalRange: { min: 0, max: 5000 },
		description: "Dissolved solids concentration",
		tags: ["solids", "dissolved", "salinity"],
		suggestedSource: "imported",
	},
	{
		id: "conductivity",
		label: "Conductivity",
		category: "physical",
		targetSection: "water-quality",
		relevantSectors: ["municipal", "commercial", "industrial"],
		importance: "optional",
		type: "unit",
		defaultUnit: "µS/cm",
		availableUnits: ["µS/cm", "mS/cm"],
		defaultValue: 800,
		typicalRange: { min: 0, max: 5000 },
		description: "Electrical conductivity",
		tags: ["conductivity", "electrical"],
		suggestedSource: "imported",
	},
];
