/**
 * REGULATORY PARAMETERS
 *
 * Parameters related to regulatory compliance and standards.
 * Includes drinking water standards, discharge standards, permits, codes.
 */

import type { ParameterDefinition } from "../types";

export const regulatoryParameters: ParameterDefinition[] = [
	{
		id: "drinking-water-standard",
		label: "Drinking Water Standard",
		category: "regulatory",
		targetSection: "regulatory-compliance",
		relevantSectors: ["municipal", "commercial", "residential"],
		importance: "optional",
		type: "combobox",
		defaultValue: "",
		description: "Applicable potable water quality standard",
		tags: ["standard", "regulation", "drinking-water"],
		suggestedSource: "manual",
		options: [
			"RTCR-25991 (CR - Drinking)",
			"NOM-127 (MX - Drinking)",
			"WHO Guidelines (Drinking)",
			"EPA NPDWR (US - Drinking)",
			"EU 2020/2184 (Drinking)",
			"Not Applicable",
		],
		placeholder: "Select or type applicable standard...",
	},
	{
		id: "discharge-standard",
		label: "Discharge / Effluent Standard",
		category: "regulatory",
		targetSection: "regulatory-compliance",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "optional",
		type: "combobox",
		defaultValue: "",
		description: "Applicable wastewater discharge standard",
		tags: ["standard", "regulation", "discharge", "effluent"],
		suggestedSource: "manual",
		options: [
			"Reglamento Vertido (CR)",
			"NOM-001 (MX - Discharge)",
			"NOM-002 (MX - Rivers)",
			"NOM-003 (MX - Reuse)",
			"EPA Clean Water Act (US)",
			"EU 91/271 (Urban WW)",
			"Not Applicable",
		],
		placeholder: "Select or type applicable standard...",
	},
	{
		id: "permit-required",
		label: "Environmental Permit Required",
		category: "regulatory",
		targetSection: "regulatory-compliance",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "optional",
		type: "select",
		defaultValue: "",
		description: "Whether environmental permit is required for operation",
		tags: ["permit", "authorization", "compliance"],
		suggestedSource: "manual",
		options: ["Yes - In Process", "Yes - Already Obtained", "No", "Unknown"],
	},
	{
		id: "seismic-code",
		label: "Seismic Design Code",
		category: "regulatory",
		targetSection: "regulatory-compliance",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "optional",
		type: "combobox",
		defaultValue: "",
		description: "Seismic code for structural design (if applicable)",
		tags: ["seismic", "earthquake", "structural"],
		suggestedSource: "manual",
		options: [
			"CSCR-2010 (Costa Rica)",
			"CFE (Mexico)",
			"IBC 2018 (USA)",
			"UBC 1997 (USA)",
			"Eurocode 8 (Europe)",
			"Not applicable",
		],
		placeholder: "Select or type seismic code...",
	},
	{
		id: "operation-manual",
		label: "Operation & Maintenance Manual",
		category: "regulatory",
		targetSection: "regulatory-compliance",
		relevantSectors: ["municipal", "commercial", "industrial", "residential"],
		importance: "optional",
		type: "select",
		defaultValue: "",
		description: "O&M manual requirements",
		tags: ["manual", "documentation", "O&M"],
		suggestedSource: "manual",
		options: [
			"Included in project",
			"Separate deliverable",
			"Not required",
			"Client will provide",
		],
	},
];
