/**
 * Application Constants
 * Consolidated from constants/project.ts and constants/ui.ts
 */

// ==============================================
// DATA SOURCES & FIELD TYPES
// ==============================================

export const DATA_SOURCES = ["manual", "imported", "ai"] as const;
export type DataSource = (typeof DATA_SOURCES)[number];

export const FIELD_IMPORTANCE = [
	"critical",
	"recommended",
	"optional",
] as const;
export type FieldImportance = (typeof FIELD_IMPORTANCE)[number];

export const FIELD_TYPES = [
	"text",
	"number",
	"select",
	"unit",
	"tags",
	"combobox",
] as const;
export type FieldType = (typeof FIELD_TYPES)[number];

// ==============================================
// TECHNICAL DATA CONFIG
// ==============================================

export const TECHNICAL_DATA_CONFIG = {
	// Completion thresholds
	COMPLETION_THRESHOLD: 70,
	HIGH_COMPLETION_THRESHOLD: 90,

	// UI limits
	MAX_FIELDS_PER_SECTION: 50,
	MAX_SECTIONS_PER_PROJECT: 20,
	MAX_FIELD_LABEL_LENGTH: 100,
	MAX_SECTION_TITLE_LENGTH: 80,

	// Performance
	AUTO_SAVE_DEBOUNCE_MS: 1000,
	SEARCH_DEBOUNCE_MS: 300,

	// Validation
	MIN_PROJECT_NAME_LENGTH: 3,
	MAX_PROJECT_NAME_LENGTH: 100,
	MIN_CLIENT_NAME_LENGTH: 2,
} as const;

// ==============================================
// PROJECT DEFAULTS
// ==============================================

export const PROJECT_DEFAULTS = {
	STATUS: "In Preparation" as const,
	PROGRESS: 0,
	BUDGET: 0,
	PROPOSALS_COUNT: 0,
	TYPE: "To be defined",
	SCHEDULE_SUMMARY: "To be defined",
} as const;

// ==============================================
// UI & UX CONSTANTS
// ==============================================

export const ANIMATION = {
	DURATION: {
		FAST: 150,
		NORMAL: 250,
		SLOW: 500,
	},
	EASING: "cubic-bezier(0.32, 0.72, 0, 1)",
} as const;

export const SOURCE_CONFIG = {
	manual: {
		label: "Manual",
		variant: "outline" as const,
		icon: "Edit3",
		color: "text-blue-600",
		description: "Fields entered directly by your team",
	},
	imported: {
		label: "Imported",
		variant: "secondary" as const,
		icon: "Upload",
		color: "text-green-600",
		description: "Data from files or integrations",
	},
	ai: {
		label: "AI",
		variant: "default" as const,
		icon: "Bot",
		color: "text-purple-600",
		description: "Suggestions generated by AI agents",
	},
} as const;

export const IMPORTANCE_CONFIG = {
	critical: {
		label: "Critical",
		color: "bg-red-100 text-red-800 border-red-200",
		description: "Required field that blocks progress if empty",
	},
	recommended: {
		label: "Recommended",
		color: "bg-amber-100 text-amber-800 border-amber-200",
		description: "Suggested for engineering, but does not block workflow",
	},
	optional: {
		label: "Optional",
		color: "bg-gray-100 text-gray-600 border-gray-200",
		description: "Contextual information completed by user as applicable",
	},
} as const;

export const NOTIFICATIONS = {
	SUCCESS_DURATION: 3000,
	ERROR_DURATION: 5000,
	WARNING_DURATION: 4000,
	INFO_DURATION: 3000,
} as const;

export const BREAKPOINTS = {
	SM: 640,
	MD: 768,
	LG: 1024,
	XL: 1280,
	"2XL": 1536,
} as const;

export const LAYOUT = {
	HEADER_HEIGHT: 64,
	SIDEBAR_WIDTH: 280,
	SIDEBAR_COLLAPSED_WIDTH: 64,
	FOOTER_HEIGHT: 48,

	// Container max widths
	CONTAINER_SM: 640,
	CONTAINER_MD: 768,
	CONTAINER_LG: 1024,
	CONTAINER_XL: 1280,
	CONTAINER_2XL: 1536,
} as const;

export const FILE_UPLOAD = {
	ALLOWED_TYPES: [".xlsx", ".xls", ".pdf", ".csv"] as const,
	MAX_SIZE_MB: 10,
	MAX_FILES: 5,
	CHUNK_SIZE: 1024 * 1024, // 1MB chunks
} as const;

export const TABLE_CONFIG = {
	DEFAULT_PAGE_SIZE: 25,
	PAGE_SIZE_OPTIONS: [10, 25, 50, 100] as const,
	MAX_ROWS_FOR_CLIENT_SORTING: 1000,
	VIRTUALIZATION_THRESHOLD: 100,
} as const;
