/**
 * UI and UX related constants
 */

/**
 * Animation and timing constants
 */
export const ANIMATION = {
  DURATION: {
    FAST: 150,
    NORMAL: 250,
    SLOW: 500,
  },
  EASING: 'cubic-bezier(0.32, 0.72, 0, 1)',
} as const

/**
 * Keyboard shortcuts
 */
export const KEYBOARD_SHORTCUTS = {
  // Navigation
  NEXT_FIELD: 'Tab',
  PREV_FIELD: 'Shift+Tab',
  SEARCH: 'Ctrl+F',

  // Editing
  SAVE_FIELD: 'Enter',
  CANCEL_EDIT: 'Escape',
  EDIT_FIELD: 'F2',
  DELETE_VALUE: 'Delete',

  // Bulk actions
  SELECT_ALL: 'Ctrl+A',
  COPY: 'Ctrl+C',
  PASTE: 'Ctrl+V',
} as const

/**
 * Source configuration for data fields
 */
export const SOURCE_CONFIG = {
  manual: {
    label: 'Manual',
    variant: 'outline' as const,
    icon: 'Edit3',
    color: 'text-blue-600',
    description: 'Fields entered directly by your team',
  },
  imported: {
    label: 'Imported',
    variant: 'secondary' as const,
    icon: 'Upload',
    color: 'text-green-600',
    description: 'Data from files or integrations',
  },
  ai: {
    label: 'AI',
    variant: 'default' as const,
    icon: 'Bot',
    color: 'text-purple-600',
    description: 'Suggestions generated by AI agents',
  },
} as const

/**
 * Importance level configuration
 */
export const IMPORTANCE_CONFIG = {
  critical: {
    label: 'Critical',
    color: 'bg-red-100 text-red-800 border-red-200',
    description: 'Required field that blocks progress if empty',
  },
  recommended: {
    label: 'Recommended',
    color: 'bg-amber-100 text-amber-800 border-amber-200',
    description: 'Suggested for engineering, but does not block workflow',
  },
  optional: {
    label: 'Optional',
    color: 'bg-gray-100 text-gray-600 border-gray-200',
    description: 'Contextual information completed by user as applicable',
  },
} as const

/**
 * Toast and notification settings
 */
export const NOTIFICATIONS = {
  SUCCESS_DURATION: 3000,
  ERROR_DURATION: 5000,
  WARNING_DURATION: 4000,
  INFO_DURATION: 3000,
} as const

/**
 * Responsive breakpoints (matching Tailwind defaults)
 */
export const BREAKPOINTS = {
  SM: 640,
  MD: 768,
  LG: 1024,
  XL: 1280,
  '2XL': 1536,
} as const

/**
 * Layout and spacing constants
 */
export const LAYOUT = {
  HEADER_HEIGHT: 64,
  SIDEBAR_WIDTH: 280,
  SIDEBAR_COLLAPSED_WIDTH: 64,
  FOOTER_HEIGHT: 48,

  // Container max widths
  CONTAINER_SM: 640,
  CONTAINER_MD: 768,
  CONTAINER_LG: 1024,
  CONTAINER_XL: 1280,
  CONTAINER_2XL: 1536,
} as const

/**
 * File upload configuration
 */
export const FILE_UPLOAD = {
  ALLOWED_TYPES: ['.xlsx', '.xls', '.pdf', '.csv'] as const,
  MAX_SIZE_MB: 10,
  MAX_FILES: 5,
  CHUNK_SIZE: 1024 * 1024, // 1MB chunks
} as const

/**
 * Table and data display settings
 */
export const TABLE_CONFIG = {
  DEFAULT_PAGE_SIZE: 25,
  PAGE_SIZE_OPTIONS: [10, 25, 50, 100] as const,
  MAX_ROWS_FOR_CLIENT_SORTING: 1000,
  VIRTUALIZATION_THRESHOLD: 100,
} as const